# Generated by Django 4.2.2 on 2023-06-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='created',
            new_name='created_at',
        ),
    ]
